development:
  :address: localhost
  :port: 25
  #:authentication: plain
  #:user_name: user
  #:password: pass
  :domain: localhost
  
production:
  :address: localhost
  :port: 25
  #:authentication: plain
  #:user_name: user
  #:password: pass
  :domain: teamportfolios.com
  #:enable_starttls_auto: false
