development:
  :address: localhost
  :port: 25
  #:authentication: plain
  #:user_name: user
  #:password: pass
  :enable_starttls_auto: false
  
production:
  :address: localhost
  :port: 25
  #:authentication: plain
  #:user_name: user
  #:password: pass
  :enable_starttls_auto: false
